### ISSUE TITLE
Possibility to redirect a path without the path being a 404

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusRedirectPlugin#1]
Say you have a landing page for christmas,  `/christmas` that you want to redirect to the frontpage when christmas is over, but you don't want to delete the page because you can reuse it next year.

In the current implementation this isn't possible, but if the listener looked in the redirection table on every request this would be possible.

However, this comes with a speed cost. If the redirection table has thousands or even millions of rows and you had to lookup the path on every request it would slow down the request. Could this problem be fixed with some kind of cache?

**Comment by Roshyo** [comment]
Agreed,

concerning the speed issue, I think it's quite insignificant. You'll rarely (never ?) have even a thousand redirections. Even with this amount, you can still index the "source" column of the table.

An other approach would be to have an option in the routing declaration like : "redirect 404 only" or "redirect all requests that matches" and have both approaches. Int/booleans are way faster than strings to filter for MySQL.

**Comment by Roshyo** [comment]
An other use case would be to disable a specific page like "/taxons/stickers" because you temporarily want to stop the sticker selling. You won't delete this route (and maybe you can't simply). SO you need to redirect it.

**Comment by Roshyo** [comment]
Here you are ! #2

**Comment by loevgaard** [comment]
Fixed by #2
