### ISSUE TITLE
Doesn't Work on PostGres

### ISSUE THREAD

**Issue by acornforth** [Setono/SyliusRedirectPlugin#11]
I assume this issue will also affect other database back-end that have a native boolean type.

the issue is in the queries in the repository, doing a comparison of a boolean filed type against an integer literal only works in mysql, and works because internally doctrine stores boolean values as tinyint in mysql. for databases with a native boolean type, this needs to be a boolean comparison.

Happy to submit a PR for review, but i will not be able to test my changes on a mysql backend.

**Comment by loevgaard** [comment]
Hi @acornforth 

Thank you very much for your issue.

It would be very much appreciated if you'd provide a PR :-)

**Comment by acornforth** [comment]
created PR #12
