### ISSUE TITLE
[ENHANCEMENT] Add a listener on product slug change to create automatic redirection

### ISSUE THREAD

**Issue by Roshyo** [Setono/SyliusRedirectPlugin#14]
It would be cool to add a listener to product slug change in order to automatically create a redirection from source slug to target.
Of course, it would be manageable in admin section to avoid creating a lot of redirections when not needed. Or even a checkbox displaying when you unlock the `lock` to modify slug.

**Comment by loevgaard** [comment]
Yes, as we discussed, this is a really good addition to this plugin.

**Comment by loevgaard** [comment]
Fixed in #16
