### ISSUE TITLE
'Last redirect' functionality is a mess

### ISSUE THREAD

**Issue by loevgaard** [Setono/SyliusRedirectPlugin#21]
Instead of having a hierarchy of redirects it would be much better to have functionality that updated the redirect hierarchy when adding a new redirect so that all redirects always pointed to the *last* destination and not any intermediary destination

**Comment by Roshyo** [comment]
But an important point of doing so is that you can completely lose something if you create `by mistake` a redirect, or create it to be temporary.

IE: `A` points to `B` and is aimed to be a permanent one.
You create a temporary marketing path that aims to redirect users from `B` to `C`. It then results in `A` to `C` and `B` to `C`. One week later, you delete this temporary redirect. And you no longer have from `A` to `B`

**Comment by loevgaard** [comment]
My idea is this:

You have one redirect: `A -> B`.

Then you create a new redirect: `B -> C`. In the background we would instead create these redirects:
- `A -> C`
- `B -> C`

Don't you think that would be the right approach?

**Comment by Roshyo** [comment]
What if your `B -> C` is just a temporary redirect or a mistake that will (in both cases) be deleted afterwards (the minute later or the month later)

Then the original `A -> C` will be quite lost because `C` page does not (no longer ?)  exists.

**Comment by loevgaard** [comment]
Good point. I will think this over. It could be solved by having a `old_destination` property on the `Redirect`, but I am not sure that is the best approach. Thanks!

**Comment by loevgaard** [comment]
Maybe use a materialized path to fix this problem: https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/tree.md#materialized-path

**Comment by Roshyo** [comment]
Just one question. What bothers you in the `lastRedirect` functionality ?

**Comment by loevgaard** [comment]
In my mind it just makes sense that it's possible to retrieve a redirect from a source and get the final destination. That would be a good experience DX wise I suppose

**Comment by loevgaard** [comment]
Closed after #28. This PR adheres to the old functionality, but makes it more encapsulated in one object
