### ISSUE TITLE
Custom http codes

### ISSUE THREAD

**Issue by ianwijma** [Setono/SyliusRedirectPlugin#36]
I was wondering if there is interest in allowing custom response codes other then 301 & 302. For example 307 (Temporary Redirect)?

**Comment by loevgaard** [comment]
Hi @ianwijma 

I know there are other redirect status codes, but I am wondering if the end user would 1) know what to do with these status codes and then subsequently 2) would they be used?

I guess in 90-95% of the cases people use redirects for 301.

What are your thoughts?

**Comment by Roshyo** [comment]
The purpose of the HTTP response code (in our case of full stack ecommerce) is mainly for indexing bots.

So in my opinion :

1/ Those who will create/update URL have to know those code and what they are used for.

2/ We must provide the code that are read by robots. In our case, 301 and 302 should be enough. The other redirect code are either complicated to generate (300, 304) or quite useless (303, 305, 307)

**Comment by Roshyo** [comment]
I've just read an interesting thing on Sylius slack : https://sylius-devs.slack.com/archives/CKANF31KQ/p1573642182073000

**Comment by ianwijma** [comment]
Hhmm yeah, I do agree. anything else then 301 & 302 does not make much sense from a webshop standpoint.
