### ISSUE TITLE
[ENHANCEMENT] Add a listener on taxon slug change to create automatic redirection

### ISSUE THREAD

**Issue by Roshyo** [Setono/SyliusRedirectPlugin#38]
Same as the one for products, we should now create it for Taxon.

**Comment by stefandoorn** [comment]
Any update on this, @Roshyo @loevgaard? Would be a great add-on.

**Comment by Roshyo** [comment]
Still not started in any way. Would you like to do that ?

**Comment by stefandoorn** [comment]
:-) Yes, actually working on it. Not sure whether I can provide Behat though as I don't have a proper dev env running for it..
