### ISSUE TITLE
Requirement to install thecodingmachine/safe?

### ISSUE THREAD

**Issue by pcmltd** [Setono/SyliusRedirectPlugin#45]
Hi,
Using an install of Sylius 1.7.3, creating a redirect and then accessing it causes a 500 error:

`"Attempted to load class "DateTime" from namespace "Safe". Did you forget a "use" statement...`

in 
`vendor/setono/sylius-redirect-plugin/src/Model/Redirect.php, line 108`

It seems the `thecodingmachine/safe` should be required in the `composer.json` but isn't. Is it assumed it's installed elsewhere?

**Comment by loevgaard** [comment]
Hi @pcmltd 

Thanks for reporting that.

I will fix it now. Give me 15 minutes :)

**Comment by pcmltd** [comment]
That's great, thanks.

**Comment by loevgaard** [comment]
Update to `v2.0.1` and it should be fixed :)

**Comment by pcmltd** [comment]
That does the job, thank you for such a speedy fix.

**Comment by loevgaard** [comment]
You are welcome :)
