### ISSUE TITLE
Installation on SF 3.4 / Sylius 1.4 fails

### ISSUE THREAD

**Issue by stefandoorn** [Setono/SyliusRedirectPlugin#46]
After following the installation instructions, I run into the following error:

```
"form.type_extension" tagged services must have the extended type configured using the extended_type/extended-type attribute, none was configured for the "setono_sylius_redirect.form.extension.product_translation" service.
```

I'm assuming for now that it's an incompatibility with Symfony 3.4, but I will do a bit of research also.

**Comment by stefandoorn** [comment]
PR in #47

**Comment by loevgaard** [comment]
Will this just be ignored in later versions of Symfony?

**Comment by loevgaard** [comment]
For sure, we will not support SF3.4 in the future, @stefandoorn. So keep those apps up to date :D
