### ISSUE TITLE
app_dev.php gets prepended

### ISSUE THREAD

**Issue by stefandoorn** [Setono/SyliusRedirectPlugin#49]
On redirect generation (when changing product slug) the `app_dev.php` file is prepended when on Symfony 3.4 and developing locally. The controller subscriber doesn't strip this off, so a redirect is never found in the end.

**Comment by Roshyo** [comment]
So what you propose would be to strip it off while inserting in DB, and if we are coming from a route with `app_dev.php` re-add it to the redirect ?
I guess that's possible, but much effort for a Symfony 3 feature :/

**Comment by stefandoorn** [comment]
Yes, I must say I don't have the best solution to it.. it's also only an issue for local development as far as I see right now.

**Comment by loevgaard** [comment]
I would say for this issue, if we can't make a generic change that fixes this, but is also useful on SF4/5 then I would have to close this, since we don't have the resources to support SF3 :(
