### ISSUE TITLE
Incompatibility with Sylius 1.9

### ISSUE THREAD

**Issue by MacBim** [Setono/SyliusRedirectPlugin#71]
Plugin version : `v2.1.1`
Sylius version : `1.9`

With the recent Sylius 1.9 update, the plugin is not compatible anymore and won't work
You systematically get this error :

`
Argument 1 passed to Setono\SyliusRedirectPlugin\EventListener\NotFoundSubscriber::__construct() must be an instance of Doctrine\Common\Persistence\ObjectManager, instance of EntityManager_9a5be93 given, called in /Users/user/PhpstormProjects/sylius/var/cache/dev/ContainerXhzYauW/getSetonoSyliusRedirect_EventListener_NotFoundService.php on line 11 
`

**Comment by loevgaard** [comment]
Can you make a PR fixing this? :)

**Comment by MacBim** [comment]
Sure, I'll submit a PR shortly !

**Comment by loevgaard** [comment]
Cool :)

**Comment by MacBim** [comment]
Here is the PR : https://github.com/Setono/SyliusRedirectPlugin/pull/72

**Comment by MacBim** [comment]
@loevgaard A follow-up to PR #72 : I forgot to actually updates the dependencies of the plugin. This should be fixed in #73
